version: '3.4'
services:
  bot:
    build: .
    volumes:
      - ./data:/bot/data:rw
    env_file:
      - bot.env
    # profiles:
    #   - prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  # dev-bot:
  #   build: .
  #   volumes:
  #     - ./data:/bot/data:rw
  #   env_file:
  #     - bot.env
  #   profiles:
  #     - dev
