version: '3.4'
services:
  bot:
    build: .
    volumes:
      - ./data:/bot/data:rw
      - ./logs:/bot/logs:rw
    env_file:
      - bot.env
    # profiles:
    #   - prod
    restart: always

  # dev-bot:
  #   build: .
  #   volumes:
  #     - ./data:/bot/data:rw
  #     - ./logs:/bot/logs:rw
  #   env_file:
  #     - bot.env
  #   profiles:
  #     - dev
