services:
  bot:
    build: .
    env_file:
      - bot.env
    volumes:
      - ./google_credentials.json:/bot/google_credentials.json
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
